version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: banco
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: docker
    networks:
      - production-network
    ports:
      - "5432:5432"
  api:
    image: vinicionagel/api:latest
    container_name: api
    links:
      - "postgres:dataBase"
    ports:
      - "8080:8080"
    networks:
      - production-network
  web:
    image: vinicionagel/web:latest
    container_name: web
    ports:
      - "4200:80"
    networks:
      - production-network
networks:
  production-network:
    driver: bridge